### ISSUE TITLE
This is under piano not team

### ISSUE THREAD

**Issue by ghost** [pianoman373/Game-Engine#1]
^^^

**Comment by pianoman373** [comment]
Are you talking about the package names or the whole project? If you want the project under team then kal is the only one with permissions to set that up.

Message.sender = "Joseph";

**Comment by ghost** [comment]
i meant the whole project. 

ParkeMc01 

On 2016-04-27 12:44, pianoman373 wrote: 

> Are you talking about the package names or the whole project? If you want the project under team then kal is the only one with permissions to set that up.
> 
> Message.sender = "Joseph";
> 
> > On Apr 27, 2016, at 12:00 PM, ParkerMc01 notifications@github.com wrote:
> > 
> > ^^^
> > 
> > ## 
> > 
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]

## Links:

[1]
https://github.com/pianoman373/Game-Engine/issues/1#issuecomment-215167829

**Comment by pianoman373** [comment]
Well kal can clone the repository to TEAM whenever he wants to.

**Comment by Kalman98** [comment]
I cannot really put this under TEAM Modding because it is not a mod. If we were to start making games together, we would need a new name.

**Comment by ghost** [comment]
ok
